version: '3'
services:
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    image: gateway-service
    ports:
      - "8082:8082"
    depends_on:
      - db
      - redis
    networks:
      - micro-back

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config-server
    image: config-server
    ports:
      - "8881:8881"
    networks:
      - micro-back
    depends_on:
      - rabbitmq

  db:
    image: mysql
    container_name: mysql001
    volumes:
      - /docker/mysql/data:/var/lib/mysql
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - micro-back

  redis:
    image: redis
    container_name: redis001
    ports:
      - "6379:6379"
    networks:
      - micro-back

  rabbitmq:
    image: rabbitmq:3.6.12-management
    container_name: myrabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15674:15674"
    command: bash -c "cd /etc/rabbitmq && rabbitmq-plugins enable rabbitmq_web_stomp"
    networks:
      - micro-back

networks:
  micro-back:
    driver: bridge
