version: '3'
services:
  elasticsearch:
    image: elasticsearch:5.6.3
    container_name: elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
       - /docker/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - micro-back

  logstash:
    image: logstash:5.6.3
    container_name: logstash
    ports:
      - "4560:4560"
    volumes:
      - /docker/logstash/config/:/usr/share/logstash/config/
    command: logstash -f /usr/share/logstash/config/logstash.conf
    networks:
      - micro-back

  kibana:
    image: kibana:5.6.3
    container_name: kibana
    environment:
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"
    networks:
      - micro-back

networks:
  micro-back:
    driver: bridge
